---
title: "Plots for paper"
output: html_notebook
---

# Description
Plotting for the paper

# Libraries
```{r Libraries, message=FALSE}
library(ggplot2)
library(DESeq2)
library("pheatmap")
library("RColorBrewer")
library(dplyr)
library(gprofiler2)
```

# Load data
```{r}
mRNA_dds <- readRDS(file = "../01-Exploratory_analysis_and_differential_expression/outputs/RDS/mRNA_dds.rds")
mir_dds <- readRDS(file = "../01-Exploratory_analysis_and_differential_expression/outputs/RDS/mir_dds.rds")
rnb_set <- readRDS(file = "../01-Exploratory_analysis_and_differential_expression/outputs/RDS/rnb_set.rds")

# This table is the one for the paper, but contains all samples so its usefull
samples_ppr <- readxl::read_xlsx("samples.xlsx")


```


# miR distance
Since I made a presentable PCA plot for mRNA data I will first make sample distance plot for miR
```{r }
# Variance stabilizng 
mir_rld <- rlog(mir_dds)
# calculating sample distance matrix
sampleDist_mir <- stats::dist(t(assay(mir_rld)), method = "euclidean")
sampleDist_mir <- as.data.frame(as.matrix(sampleDist_mir))
```


```{r}
colors <- colorRampPalette( rev(brewer.pal(9, "Oranges")) )(255)

annot_col <- list(
  # Tumor colors
  Hist = setNames(c(brewer.pal(8, "Reds")[7],  brewer.pal(8, "Blues")[7]),
                   c("cancer", "control")),
  # HPV colors
  HPV = setNames( c("forestgreen","gold"), 
                  c("P","N")),
  # Tissue colors
  Tissue = setNames(c(brewer.pal(8, "Dark2")[3], brewer.pal(8, "Dark2")[7]),
                    c("OP","O"))
)

annot_data <- colData(mir_rld) %>% 
  as.data.frame() %>%
  dplyr::select(Hist, HPV, Tissue) %>%
  # changing normal to control in Hist
  mutate(Hist = ifelse(Hist == "normal", "control", "cancer"))


pheatmap(sampleDist_mir,
         # clustering_distance_rows = sampleDist_mir,
         # clustering_distance_cols = sampleDist_mir,
         cluster_rows = TRUE,
         cluster_cols = TRUE,
         col = colors,
         treeheight_col = 0,
         treeheight_row = 0,
         #annotation_row = annot_data,
         annotation_col = annot_data,
         annotation_colors = annot_col,
         show_colnames = FALSE,
         show_rownames = FALSE,
         annotation_names_col = FALSE,
         fontsize = 20,
         width = 10,
         cellwidth = 25,
         filename ="plots/sampleDistance_miR.png")
```


# DNAm distance
```{r}
# Novariance stabilizarion?
# calculating sample distance matrix
sampleDist_dnam <- stats::dist(t(meth(rnb_set)))
sampleDist_dnam <- as.data.frame(as.matrix(sampleDist_dnam))
```

```{r}
colors <- colorRampPalette( rev(brewer.pal(9, "Greens")) )(255)

annot_col <- list(
  # Tumor colors
  Hist = setNames(c(brewer.pal(8, "Reds")[7],  brewer.pal(8, "Blues")[7]),
                   c("cancer", "control")),
  # HPV colors
  HPV = setNames( c("forestgreen","gold"), 
                  c("P","N")),
  # Tissue colors
  Tissue = setNames(c(brewer.pal(8, "Dark2")[3], brewer.pal(8, "Dark2")[7]),
                    c("OP","O"))
)



annot_data <- pheno(rnb_set) %>% 
  as.data.frame() %>%
  dplyr::mutate(Hist = ifelse(Sample_group == "Cancer", "cancer", "control")) %>%
  dplyr::select(Sample_ID, Hist, HPV) %>%
  # Adding tissue locations from sample_ppr table 
  left_join(select(samples_ppr,ID, Tissue = "Location") %>%
              mutate(ID=tolower(ID)),
            by = c("Sample_ID" = "ID")) %>%
  dplyr::select(everything(), - Sample_ID)


rownames(annot_data) <- pheno(rnb_set)$Sample_ID

pheatmap(sampleDist_dnam,
         # clustering_distance_rows = sampleDist_dnam,
         # clustering_distance_cols = sampleDist_dnam,
         col = colors,
         treeheight_col = 0,
         treeheight_row = 0,
         #annotation_row = annot_data,
         annotation_col = annot_data,
         annotation_colors = annot_col,
         show_colnames = FALSE,
         show_rownames = FALSE,
         annotation_names_col = FALSE,
         fontsize = 20,
         width = 10,
         cellwidth = 25,
         filename ="plots/sampleDistance_dnam.png")

```


# DE expression gsea

## Loading data
```{r}
mRNA_res <- readRDS("../01-Exploratory_analysis_and_differential_expression/outputs/RDS/mRNA_res.rds")


```


```{r}
mRNA_gost <- as.data.frame(mRNA_res)%>%
  filter(padj < 0.05) %>%
  rownames() %>%
  unique()


# Using only part of sources
GSEA_SOURCES <- c("GO:BP","KEGG","REAC")


# Call on the gost 
mRNA_gost <- 
  gost(mRNA_gost,
       organism= "hsapiens",
       exclude_iea=TRUE,
       domain_scope="annotated",
       ordered_query=F,
       sources=GSEA_SOURCES)

# Change query name
mRNA_gost$result$query <- ""

#Plot and table of significant results
gostplot(mRNA_gost ,capped = F, interactive = T)

publish_gostplot(gostplot(mRNA_gost ,capped = F, interactive = F),
                 highlight_terms = read.csv("GSEA_terms.txt", 
                                            header = F)[,1],
                 filename = "plots/gost_plot_mRNA_highlighted.png")
```

# mir targets histograms
will not be doing that
## Loading data
```{r}
targ_mir_mRNA <- 
  readRDS( "../02-Regulation_targets/outputs/RDS/targ_mir_mRNA.rds")

cor_mir <-
  readRDS("../02-Regulation_targets/outputs/RDS/cor_mir.rds")
```

## plot
```{r}
mir_freq <- 
  table(cor_mir$mir) %>%
  as.data.frame()


ggplot(mir_freq, aes(Freq))+
  geom_histogram()+
  stat_bin(binwidth = 1, bins = 50)
```
# Mir mRNA scatterplots

```{r}

```


# Session Info
```{r Session info}
sessionInfo()
```
