---
title: "Preparing some plots for poster"
output: html_notebook
---

# Description
Insert the descripiton of the notebook here.

# Libraries
```{r Libraries, message=FALSE}
library(RColorBrewer)
library(ggplot2)
```

# PCA plot on mRNA data
```{r}
# selecting data for plotting pca
mRNA_pcadata <- 
  DESeq2::plotPCA(mRNA_rld, 
                  intgroup = c("Hist", "HPV", "Tissue"),
                  returnData = TRUE) %>%
  dplyr::rename(Sample ="Hist") %>%
  mutate(HPV = ifelse(HPV==1, "P","N"))
# selecting variance
percentVar <- round(100 * attr(mRNA_pcadata, "percentVar"))


# Color for PCA 
col_pca <- c(
  # Dark red
  brewer.pal(8, "Reds")[7],
  brewer.pal(8, "Blues")[7]
)


# plotting pca data
ggplot(mRNA_pcadata, aes(x = PC1, y = PC2, color = Sample, shape = HPV)) +
  geom_point(size =3) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
   theme(#panel.grid = element_blank(), 
         panel.background = element_rect(fill = brewer.pal(1,"Greys")[1]),
         panel.border = element_rect(fill = "transparent"),
         legend.key=element_blank(),
         axis.title=element_text(size=18),
         legend.text=element_text(size=20),
         legend.title=element_text(size=20))+
  coord_fixed() +
  #ggtitle("PCA with rlog data")+
  scale_color_manual(values = col_pca)+
  scale_fill_manual(values= c("pink", "white"))+
  ggsave(filename = "plots/PCA_mRNA.png")
  #geom_text_repel(aes(label = colData(mRNA_rld)$Sample.ID), size =3)
  #geom_text_repel(aes(label = colData(mRNA_rld)$GRCE.NAME), size =3)
```


# DNAmethylation 
# Session Info
```{r Session info}
sessionInfo()
```
