---
title: "Title"

---

# Description
Insert the descripiton of the notebook here.

# Libraries
```{r Libraries, message=FALSE}

```


# Load data
```{r}
reg_df  <- readRDS(file.path(project_dir, "data/processed/integrated_table_per_GENE.rds"))

k_tb <- data.frame(row.names = reg_df$gene,
                   dplyr::select(reg_df,
                                 gene_FC,
                                 mir_FC,
                                 dnam_quot))
```

## 
```{r, eval=FALSE}
kmeansHeatmap(k_tb, clusters= 1:20, nstart = 100, GSEA = TRUE,
              scaled = "scaled",
              directory = file.path(project_dir, "data/output/kmeans_clusters/"),
              plot_cost = TRUE)
```


```{r}
kmeans_tb <- readRDS(file.path(project_dir, "data/output/kmeans_clusters/res/20221110_1148__11clusters_100nstart_scaled.rds"))
```

```{r}
# cl3 <- filter(kmeans_tb, kmeans == 3) 

k_tb <- data.frame(row.names = reg_df$gene,
                   dplyr::select(reg_df,
                                 gene_FC,
                                 mir_FC,
                                 dnam_quot))

for( i in 1:11){
  cl <- barPlotData(kmeans_tb, i, unscaled_data = k_tb)
  
  ggplot(cl) +
    geom_bar( aes(x=groups, y =mean), stat = "identity", fill = brewer.pal(12, "Paired")[i], color = "black") + 
    geom_errorbar( aes(x=groups, ymin=mean-sd, ymax=mean+sd), width = 0.2, alpha = 0.9, size = 1.1)+
      theme(panel.background = element_rect(fill = "white"),
           panel.border = element_rect(fill = "transparent"),
           panel.grid = element_line(color = brewer.pal(5,"Greys")[1]),
           legend.key=element_blank(),
           axis.title=element_text(size=10),
           legend.text=element_text(size=10),
           legend.title=element_text(size=10)) +
    geom_hline(yintercept = 0, color = "grey")
  
  ggsave(filename = paste0(project_dir, "/data/output/kmeans_clusters/res/bar_plots_cl",  i, "_unscaled.png"))

}


```
kmeans_full_table
```{r, eval=FALSE}
to_export <- left_join(reg_df,
                       kmeans_tb %>% 
                         tibble::rownames_to_column(var="gene") %>%
                         select(gene, kmeans))
writexl::write_xlsx(to_export, file.path(project_dir, "data/output/tables/integrated_table_per_GENE_clusters.xlsx"))
```


# Session Info
```{r Session info}
sessionInfo()
```
