---
title: "Tumor supressors from TCGA"
author: "Katarina Mandić"
date: "`r format(Sys.time(), '%d %b, %Y')`"
output:
  html_document:
    css: style.css
---


# Tumor supressors
## Description
Downloaded a list of all tumor supressor genes detected in TCGA data:
https://bioinfo.uth.edu/TSGene/download.cgi 

## Libraries
```{r Libraries, message=FALSE}
library(rprojroot)

# Leads to the project directory
project_dir <- find_rstudio_root_file()

source(file = file.path(project_dir,"src", "utils.R"))
```

## Loading data
```{r}
tcga_TS <- read.csv(file.path(project_dir,"data/input/All_down_exp_TSGs_pan-cancer.txt"), sep = "\t")
tcga_HNSC_TS <- read.csv(file.path(project_dir,"data/input/HNSC_down_regulated_TSgenes.txt"), sep = "\t",
                         header = FALSE) %>%
  dplyr::select(GeneID = "V1", GeneName="V2")

mRNA_res <- readRDS(file.path(project_dir, "data/processed/mRNA_res.rds"))

 genes_dir <- file.path(project_dir, "data","input", "genes.hg19.ensembl.rds")
```


## TS detection
Filtering out differentially expressed mRNA
```{r}
DE_mRNA <- mRNA_res %>%
  as.data.frame() %>%
  filter(padj < 0.05 )
DE_mRNA <- DE_mRNA %>%
  mutate(geneName = idMap(rownames(DE_mRNA), 
                          genes_file = genes_dir)) %>%
  dplyr::select(geneName, everything())
```


```{r}
message("Tumor suppressors that are DE in our samples")
is.element(tcga_HNSC_TS$GeneName, DE_mRNA$geneName) %>% table()
message("Tumor suppressors that are underexpressed in our samples")
is.element(tcga_HNSC_TS$GeneName, filter(DE_mRNA, log2FoldChange <= 0) %>%
             pull(geneName)) %>% table()
```


```{r}
filter(DE_mRNA, is.element(geneName,tcga_HNSC_TS$GeneName )) %>% View
```

## DM promoters
```{r}
# Downregulated Tumor supressors
DR_TS <- filter(DE_mRNA, is.element(geneName,tcga_HNSC_TS$GeneName ) & log2FoldChange < 0) 

# downregulated tumor supressor with hypermethylated tumor supressors
DR_DM_TS <- 
  plyranges::filter(dnam_res_cgi, is.element(ensembl, rownames(DR_TS)) & log.quot > 0)  %>%
  as.data.frame()



writexl::write_xlsx(
  left_join(DR_DM_TS, DE_mRNA, by = c("symbol" = "geneName")) %>%
  dplyr::mutate(CGI_coordinates= str_c(seqnames,":", start,"-", end)) %>%
  dplyr::select(ensembl, symbol, CGI_coordinates),
  path = file.path(project_dir, "data/output/tables/Downregulated_Tumor_Suppressors_with_Hypermethylated_Promoters.xlsx"))
```



# Session Info
```{r Session info}
sessionInfo()
```
